import assert from "node:assert/strict";
import { test } from "bun:test";

import { analyzePatchMinimality } from "./patchMinimalityProbes";

// ---------------------------------------------------------------------------
// Fixtures (synthetic unified diffs — no live artifacts, no agents, no Docker).
// ---------------------------------------------------------------------------

// Deletion of both PLY generated tables, with a broad grammar relocation in cds.py:
// productions move out of p_product_of_units / p_division_of_units into p_combined_units.
// Mirrors the auditable Astropy protocol run (astropy__astropy-14369).
const ASTROPY_BROAD = [
  "diff --git a/astropy/units/format/cds.py b/astropy/units/format/cds.py",
  "--- a/astropy/units/format/cds.py",
  "+++ b/astropy/units/format/cds.py",
  "@@ -164,30 +164,20 @@ class CDS(Base):",
  "         def p_combined_units(p):",
  "             \"\"\"",
  "-            combined_units : product_of_units",
  "-                           | division_of_units",
  "-            \"\"\"",
  "-            p[0] = p[1]",
  "-",
  "-        def p_product_of_units(p):",
  "-            \"\"\"",
  "-            product_of_units : unit_expression PRODUCT combined_units",
  "-                             | unit_expression",
  "+            combined_units : combined_units DIVISION unit_expression",
  "+                           | combined_units PRODUCT unit_expression",
  "+                           | DIVISION unit_expression",
  "+                           | unit_expression",
  "             \"\"\"",
  "-",
  "-        def p_division_of_units(p):",
  "-            \"\"\"",
  "-            division_of_units : DIVISION unit_expression",
  "-                              | unit_expression DIVISION combined_units",
  "-            \"\"\"",
  "             if len(p) == 4:",
  "+                p[0] = p[1]",
  "         def p_unit_expression(p):",
  "diff --git a/astropy/units/format/cds_lextab.py b/astropy/units/format/cds_lextab.py",
  "deleted file mode 100644",
  "--- a/astropy/units/format/cds_lextab.py",
  "+++ /dev/null",
  "@@ -1,3 +0,0 @@",
  "-# cds_lextab.py generated by PLY",
  "-_tabversion = '3.10'",
  "-_lextokens = set()",
  "diff --git a/astropy/units/format/cds_parsetab.py b/astropy/units/format/cds_parsetab.py",
  "deleted file mode 100644",
  "--- a/astropy/units/format/cds_parsetab.py",
  "+++ /dev/null",
  "@@ -1,3 +0,0 @@",
  "-# cds_parsetab.py generated by PLY",
  "-_tabversion = '3.10'",
  "-_lr_method = 'LALR'",
].join("\n");

// Only the generated parser table is deleted; no source grammar edit accompanies it.
const TABLE_DELETION_ONLY = [
  "diff --git a/astropy/units/format/cds_parsetab.py b/astropy/units/format/cds_parsetab.py",
  "deleted file mode 100644",
  "--- a/astropy/units/format/cds_parsetab.py",
  "+++ /dev/null",
  "@@ -1,2 +0,0 @@",
  "-# cds_parsetab.py generated by PLY",
  "-_lr_method = 'LALR'",
].join("\n");

// A single parser function p_division_of_units is removed (broad: production relocation).
const REMOVED_PARSER_FN = [
  "diff --git a/astropy/units/format/cds.py b/astropy/units/format/cds.py",
  "--- a/astropy/units/format/cds.py",
  "+++ b/astropy/units/format/cds.py",
  "@@ -188,8 +188,2 @@ class CDS(Base):",
  "         def p_combined_units(p):",
  "             pass",
  "-",
  "-        def p_division_of_units(p):",
  "-            \"\"\"",
  "-            division_of_units : DIVISION unit_expression",
  "-                              | unit_expression DIVISION combined_units",
  "-            \"\"\"",
  "-            p[0] = p[1]",
].join("\n");

// Two parser functions changed (productions relocated across functions), no removal.
const RELOCATED_ACROSS_FUNCTIONS = [
  "diff --git a/pkg/grammar.py b/pkg/grammar.py",
  "--- a/pkg/grammar.py",
  "+++ b/pkg/grammar.py",
  "@@ -10,4 +10,4 @@",
  "         def p_expr(p):",
  "             \"\"\"",
  "-            expr : term PLUS expr",
  "+            expr : term",
  "             \"\"\"",
  "@@ -30,4 +30,4 @@",
  "         def p_term(p):",
  "             \"\"\"",
  "-            term : factor",
  "+            term : factor TIMES term",
  "             \"\"\"",
].join("\n");

// Narrow one-line grammar production reorder inside a single parser function — the
// known-good shape. Must NOT be flagged high-risk.
const NARROW_REORDER = [
  "diff --git a/astropy/units/format/cds.py b/astropy/units/format/cds.py",
  "--- a/astropy/units/format/cds.py",
  "+++ b/astropy/units/format/cds.py",
  "@@ -190,3 +190,3 @@ class CDS(Base):",
  "         def p_division_of_units(p):",
  "             \"\"\"",
  "-            division_of_units : unit_expression DIVISION combined_units",
  "+            division_of_units : combined_units DIVISION unit_expression",
  "             \"\"\"",
].join("\n");

// Ordinary, non-parser source edit.
const ORDINARY_EDIT = [
  "diff --git a/src/util.py b/src/util.py",
  "--- a/src/util.py",
  "+++ b/src/util.py",
  "@@ -5,3 +5,3 @@ def compute(x):",
  "-    return x + 1",
  "+    return x + 2",
].join("\n");

// ---------------------------------------------------------------------------
// 1. Detects generated parser table deletion from a unified diff.
// ---------------------------------------------------------------------------
test("detects generated parser table deletion", () => {
  const r = analyzePatchMinimality(TABLE_DELETION_ONLY);
  assert.deepEqual(r.generatedFilesDeleted, ["astropy/units/format/cds_parsetab.py"]);
  assert.equal(r.defectClass, "generated_parser_table_deletion");
  assert.equal(r.risk, "high");
  assert.ok(r.signals.includes("generated_parser_table_deleted"));
});

// ---------------------------------------------------------------------------
// 2. Detects broad grammar rewrite when productions relocated across functions.
// ---------------------------------------------------------------------------
test("detects broad grammar rewrite across parser functions", () => {
  const r = analyzePatchMinimality(RELOCATED_ACROSS_FUNCTIONS);
  assert.equal(r.broadRewriteDetected, true);
  assert.equal(r.defectClass, "generated_parser_broad_rewrite");
  assert.deepEqual(r.grammarFunctionsChanged, ["p_expr", "p_term"]);
  assert.ok(r.signals.includes("multiple_grammar_functions_changed"));
  assert.ok(r.risk === "medium" || r.risk === "high");
});

// ---------------------------------------------------------------------------
// 3. Detects a removed parser function such as p_division_of_units.
// ---------------------------------------------------------------------------
test("detects a removed parser function", () => {
  const r = analyzePatchMinimality(REMOVED_PARSER_FN);
  assert.ok(r.grammarFunctionsRemoved.includes("p_division_of_units"));
  assert.equal(r.broadRewriteDetected, true);
  assert.equal(r.defectClass, "generated_parser_broad_rewrite");
  assert.equal(r.risk, "high");
  assert.ok(r.signals.includes("grammar_function_removed"));
});

// ---------------------------------------------------------------------------
// 4. Emits broad-rewrite + grammar-minimality for the Astropy-style fixture.
// ---------------------------------------------------------------------------
test("flags the Astropy-style fixture as broad rewrite + grammar minimality", () => {
  const r = analyzePatchMinimality(ASTROPY_BROAD);
  assert.equal(r.defectClass, "generated_parser_broad_rewrite");
  assert.equal(r.repairRequired, true);
  assert.equal(r.risk, "high");
  assert.equal(r.confidence, "high");
  // Both generated tables detected as deleted.
  assert.deepEqual(r.generatedFilesDeleted.sort(), [
    "astropy/units/format/cds_lextab.py",
    "astropy/units/format/cds_parsetab.py",
  ]);
  // Relocated productions out of p_product_of_units / p_division_of_units.
  assert.ok(r.grammarFunctionsRemoved.includes("p_product_of_units"));
  assert.ok(r.grammarFunctionsRemoved.includes("p_division_of_units"));
  assert.ok(r.broadRewriteDetected);
  // The minimality flavor is co-emitted as a signal.
  assert.ok(r.signals.includes("grammar_patch_minimality"));
  assert.ok(r.signals.includes("grammar_productions_relocated"));
});

// ---------------------------------------------------------------------------
// 5. Does not flag a narrow one-line grammar production reorder as high risk.
// ---------------------------------------------------------------------------
test("does not flag a narrow one-line production reorder as high risk", () => {
  const r = analyzePatchMinimality(NARROW_REORDER);
  assert.notEqual(r.risk, "high");
  assert.equal(r.repairRequired, false);
  assert.equal(r.broadRewriteDetected, false);
  assert.equal(r.generatedFilesDeleted.length, 0);
  assert.deepEqual(r.grammarFunctionsChanged, ["p_division_of_units"]);
  assert.equal(r.defectClass, "none");
  assert.ok(r.signals.includes("narrow_grammar_edit"));
});

// ---------------------------------------------------------------------------
// 6. Does not flag ordinary non-parser file edits.
// ---------------------------------------------------------------------------
test("does not flag ordinary non-parser edits", () => {
  const r = analyzePatchMinimality(ORDINARY_EDIT);
  assert.equal(r.defectClass, "none");
  assert.equal(r.risk, "low");
  assert.equal(r.repairRequired, false);
  assert.equal(r.broadRewriteDetected, false);
  assert.equal(r.generatedFilesDeleted.length, 0);
  assert.equal(r.grammarFunctionsChanged.length, 0);
});

// ---------------------------------------------------------------------------
// 7. Emits affected files and generatedFilesDeleted.
// ---------------------------------------------------------------------------
test("emits affectedFiles and generatedFilesDeleted", () => {
  const r = analyzePatchMinimality(ASTROPY_BROAD);
  assert.ok(r.affectedFiles.includes("astropy/units/format/cds.py"));
  assert.ok(r.affectedFiles.includes("astropy/units/format/cds_lextab.py"));
  assert.ok(r.affectedFiles.includes("astropy/units/format/cds_parsetab.py"));
  assert.equal(r.sourceGrammarFilesChanged.length, 1);
  assert.equal(r.sourceGrammarFilesChanged[0], "astropy/units/format/cds.py");
});

// ---------------------------------------------------------------------------
// 8. Emits narrowAlternativeHint for the Astropy-style fixture.
// ---------------------------------------------------------------------------
test("emits a narrowAlternativeHint for the Astropy-style fixture", () => {
  const r = analyzePatchMinimality(ASTROPY_BROAD);
  assert.ok(typeof r.narrowAlternativeHint === "string");
  // Hint is derived from a removed production (not hardcoded), and references not
  // relocating productions / deleting generated tables.
  assert.ok(/production/i.test(r.narrowAlternativeHint!));
  assert.ok(/generated parser tables/i.test(r.narrowAlternativeHint!));
});

// ---------------------------------------------------------------------------
// Options: custom grammar/parser patterns are honored.
// ---------------------------------------------------------------------------
test("honors custom generated-parser and grammar-function patterns", () => {
  const diff = [
    "diff --git a/g/yacc.tab.c b/g/yacc.tab.c",
    "deleted file mode 100644",
    "--- a/g/yacc.tab.c",
    "+++ /dev/null",
    "@@ -1,1 +0,0 @@",
    "-/* generated */",
  ].join("\n");
  // Default patterns do not match yacc.tab.c.
  assert.equal(analyzePatchMinimality(diff).generatedFilesDeleted.length, 0);
  // A custom pattern does.
  const r = analyzePatchMinimality(diff, { generatedParserFilePatterns: [/\.tab\.c$/] });
  assert.deepEqual(r.generatedFilesDeleted, ["g/yacc.tab.c"]);
  assert.equal(r.defectClass, "generated_parser_table_deletion");
});
