// Tests for generated / co-edit artifact actionability hints.
//
// Two layers: pure-detector unit tests (which path/content shapes emit a hint,
// which do not, evidence/confidence, caps), and integration tests proving the hint
// flows through the Capsule v2 product response, the human/injected-context
// render, the MCP get_context_capsule output schema, and token accounting (counted
// in estimatedOutputTokens, never inflating the naive full-file baseline).
//
// Nothing here pins instance ids or gold-patch data: the astropy-like case is built
// from a seeded grammar file + adjacent generated table, exactly as a real repo
// would carry them.

import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { test } from "bun:test";

import { detectActionabilityHints } from "./actionabilityHints";
import { buildCapsuleV2 } from "./buildCapsuleV2";
import { renderCapsuleV2Human } from "./renderHuman";
import { toCapsuleV2ProductResponse } from "./productAdapter";
import { CapsuleIntent } from "./types";
import { seedCustomFixture } from "./__fixtures__/capsuleV2Fixture";
import { SymbolKind } from "../domain/types";
import { buildContextAccounting, runPipelineOutputFilePathGroups } from "../metrics/contextAccounting";
import { RESERVED_MCP_TOOL_DEFINITIONS } from "../mcp/tools";
import { McpToolId } from "../mcp/types";

// A PLY-style grammar source body: `def p_*` functions + a yacc reference.
const GRAMMAR_BODY =
  "class CdsFormat:\n"
  + "    \"\"\"CDS unit format parser built on PLY/yacc.\"\"\"\n"
  + "    def parse(self, s):\n"
  + "        return yacc.parse(s)\n"
  + "\n"
  + "def p_division_of_units(p):\n"
  + "    '''\n"
  + "    division_of_units : DIVISION unit_expression\n"
  + "                      | unit_expression DIVISION combined_units\n"
  + "    '''\n"
  + "    p[0] = p[2]";

// A generated parser table body carrying the canonical auto-generated banner.
const PARSETAB_BODY =
  "# cds_parsetab.py\n"
  + "# This file is automatically generated. Do not edit.\n"
  + "_tabversion = '3.10'\n"
  + "_lr_method = 'LALR'";

function grammarFixture(extra: ReadonlyArray<{ relPath: string; specs: ReadonlyArray<{ localName: string; kind: SymbolKind; body: string }> }> = []) {
  return seedCustomFixture([
    {
      relPath: "astropy/units/format/cds.py",
      specs: [
        { localName: "CdsFormat", kind: SymbolKind.Class, body: GRAMMAR_BODY },
      ],
    },
    ...extra,
  ]);
}

// --- (1) grammar source + adjacent *_parsetab.py emits a hint -------------------

test("grammar source with an adjacent _parsetab.py emits a generated_artifact hint", () => {
  const { db, repoRoot } = grammarFixture([
    {
      relPath: "astropy/units/format/cds_parsetab.py",
      specs: [{ localName: "_tabversion", kind: SymbolKind.ModuleVariable, body: PARSETAB_BODY }],
    },
  ]);
  try {
    const hints = detectActionabilityHints({
      db,
      repoRoot,
      candidatePaths: ["astropy/units/format/cds.py"],
    });
    assert.equal(hints.length, 1);
    const hint = hints[0]!;
    assert.equal(hint.kind, "generated_artifact");
    assert.equal(hint.sourceFile, "astropy/units/format/cds.py");
    assert.equal(hint.relatedFile, "astropy/units/format/cds_parsetab.py");
    assert.equal(hint.confidence, "high");
    assert.ok(hint.hint.length > 0);
  } finally {
    db.close();
  }
});

// --- (2) grammar source + adjacent *_lextab.py emits a hint --------------------

test("grammar source with an adjacent _lextab.py emits a hint", () => {
  const { db, repoRoot } = grammarFixture([
    {
      relPath: "astropy/units/format/cds_lextab.py",
      specs: [{ localName: "_lextokens", kind: SymbolKind.ModuleVariable, body: PARSETAB_BODY }],
    },
  ]);
  try {
    const hints = detectActionabilityHints({
      db,
      repoRoot,
      candidatePaths: ["astropy/units/format/cds.py"],
    });
    assert.equal(hints.length, 1);
    assert.equal(hints[0]!.relatedFile, "astropy/units/format/cds_lextab.py");
  } finally {
    db.close();
  }
});

// --- (3) no hint for unrelated adjacent files ----------------------------------

test("an unrelated adjacent file (no name-linked table) emits no hint", () => {
  const { db, repoRoot } = grammarFixture([
    {
      relPath: "astropy/units/format/utils.py",
      specs: [{ localName: "helper", kind: SymbolKind.Function, body: "def helper():\n    return 1" }],
    },
  ]);
  try {
    const hints = detectActionabilityHints({
      db,
      repoRoot,
      candidatePaths: ["astropy/units/format/cds.py", "astropy/units/format/utils.py"],
    });
    assert.deepEqual(hints, []);
  } finally {
    db.close();
  }
});

// --- (4) generated-file comment evidence contributes ---------------------------

test("the adjacent table's auto-generated banner contributes to evidence and confidence", () => {
  const { db, repoRoot } = grammarFixture([
    {
      relPath: "astropy/units/format/cds_parsetab.py",
      specs: [{ localName: "_tabversion", kind: SymbolKind.ModuleVariable, body: PARSETAB_BODY }],
    },
  ]);
  try {
    const hints = detectActionabilityHints({
      db,
      repoRoot,
      candidatePaths: ["astropy/units/format/cds.py"],
    });
    const hint = hints[0]!;
    assert.ok(
      hint.evidence.some((e) => /banner/i.test(e)),
      `expected banner evidence, got ${JSON.stringify(hint.evidence)}`,
    );
    assert.equal(hint.confidence, "high");
    assert.ok(hint.evidence.length <= 2, "evidence capped at 2 bullets");
  } finally {
    db.close();
  }
});

// --- (5) hints are capped at 3 -------------------------------------------------

test("hints are capped at MAX_HINTS (3) even with more grammar/table pairs", () => {
  const extra = [];
  const candidatePaths: string[] = [];
  for (let i = 0; i < 5; i += 1) {
    extra.push({
      relPath: `pkg/g${i}/grammar.py`,
      specs: [{ localName: `Grammar${i}`, kind: SymbolKind.Class, body: GRAMMAR_BODY }],
    });
    extra.push({
      relPath: `pkg/g${i}/grammar_parsetab.py`,
      specs: [{ localName: `_tab${i}`, kind: SymbolKind.ModuleVariable, body: PARSETAB_BODY }],
    });
    candidatePaths.push(`pkg/g${i}/grammar.py`);
  }
  const { db, repoRoot } = seedCustomFixture(extra);
  try {
    const hints = detectActionabilityHints({ db, repoRoot, candidatePaths });
    assert.equal(hints.length, 3);
  } finally {
    db.close();
  }
});

// --- (6) hints reach the Capsule v2 product response (astropy-14369 shape) ------

test("Capsule v2 product response includes the cds.py -> cds_parsetab.py hint", () => {
  const { db, repoRoot } = grammarFixture([
    {
      relPath: "astropy/units/format/cds_parsetab.py",
      specs: [{ localName: "_tabversion", kind: SymbolKind.ModuleVariable, body: PARSETAB_BODY }],
    },
  ]);
  try {
    const result = buildCapsuleV2({
      db,
      repoRoot,
      task: "CDS format parsing fails when reading a units header.",
      intent: CapsuleIntent.Auto,
      maxTokens: 8_000,
    });
    // cds.py is selected (the literal anchor names it), so the detector fires.
    assert.ok(
      result.pivots.some((p) => p.path.includes("cds.py"))
        || result.support.some((s) => s.path.includes("cds.py")),
      "expected cds.py in the capsule selection",
    );
    const internal = result.actionability_hints ?? [];
    assert.ok(
      internal.some(
        (h) => h.sourceFile === "astropy/units/format/cds.py"
          && h.relatedFile === "astropy/units/format/cds_parsetab.py",
      ),
      `expected internal hint, got ${JSON.stringify(internal)}`,
    );
    const product = toCapsuleV2ProductResponse(result);
    assert.ok(Array.isArray(product.actionabilityHints));
    assert.ok(
      product.actionabilityHints.some(
        (h) => h.sourceFile === "astropy/units/format/cds.py"
          && h.relatedFile === "astropy/units/format/cds_parsetab.py",
      ),
      `expected product hint, got ${JSON.stringify(product.actionabilityHints)}`,
    );
    // Always-present field (empty array when none) so consumers can rely on it.
    assert.ok("actionabilityHints" in product);
  } finally {
    db.close();
  }
});

// --- (7) hints render into the human / Stage 5 injected context ----------------

test("renderCapsuleV2Human surfaces an Actionability hints section", () => {
  const { db, repoRoot } = grammarFixture([
    {
      relPath: "astropy/units/format/cds_parsetab.py",
      specs: [{ localName: "_tabversion", kind: SymbolKind.ModuleVariable, body: PARSETAB_BODY }],
    },
  ]);
  try {
    const result = buildCapsuleV2({
      db,
      repoRoot,
      task: "CDS format parsing fails when reading a units header.",
      intent: CapsuleIntent.Auto,
      maxTokens: 8_000,
    });
    const text = renderCapsuleV2Human(result);
    assert.ok(text.includes("## Actionability hints"), "missing hints heading");
    assert.ok(text.includes("cds_parsetab.py"), "missing related artifact in render");
  } finally {
    db.close();
  }
});

// --- (8) MCP get_context_capsule v2 schema documents the hints -----------------

test("get_context_capsule output schema documents capsuleV2.actionabilityHints", () => {
  const tool = RESERVED_MCP_TOOL_DEFINITIONS.find(
    (t) => t.metadata.toolId === McpToolId.GetContextCapsule,
  );
  assert.ok(tool, "get_context_capsule tool definition not found");
  const schema = tool!.metadata.outputSchema as {
    properties?: {
      capsuleV2?: { properties?: Record<string, unknown>; required?: string[] };
    };
  };
  const capsuleV2 = schema.properties?.capsuleV2;
  assert.ok(capsuleV2?.properties?.actionabilityHints, "schema missing actionabilityHints");
  assert.ok(
    capsuleV2?.required?.includes("actionabilityHints"),
    "actionabilityHints not in capsuleV2 required list",
  );
});

// --- (9) run_pipeline / get_code_context preserve hints (carried in capsuleV2) --

test("a run-pipeline-shaped output carries actionabilityHints inside capsuleV2", () => {
  const { db, repoRoot } = grammarFixture([
    {
      relPath: "astropy/units/format/cds_parsetab.py",
      specs: [{ localName: "_tabversion", kind: SymbolKind.ModuleVariable, body: PARSETAB_BODY }],
    },
  ]);
  try {
    const result = buildCapsuleV2({
      db,
      repoRoot,
      task: "CDS format parsing fails when reading a units header.",
      intent: CapsuleIntent.Auto,
      maxTokens: 8_000,
    });
    const product = toCapsuleV2ProductResponse(result);
    // run_pipeline emits the product response verbatim inside `capsuleV2` (a
    // structuredClone). A clone round-trip preserves the field for both
    // run_pipeline and its get_code_context alias.
    const runPipelineOutput = { capsuleV2: structuredClone(product) };
    assert.deepEqual(
      runPipelineOutput.capsuleV2.actionabilityHints,
      product.actionabilityHints,
    );
    assert.ok(runPipelineOutput.capsuleV2.actionabilityHints.length > 0);
  } finally {
    db.close();
  }
});

// --- (10) accounting counts hint text but adds no full-file baseline -----------

test("hint text counts toward estimatedOutputTokens without inflating the naive baseline", async () => {
  const repoRoot = mkdtempSync(path.join(tmpdir(), "vtrace-accounting-"));
  const hint = {
    kind: "generated_artifact" as const,
    sourceFile: "astropy/units/format/cds.py",
    relatedFile: "astropy/units/format/cds_parsetab.py",
    confidence: "high" as const,
    evidence: ["source defines PLY-style grammar functions (def p_*)"],
    hint: "If you change parser/grammar rules here, check whether the generated parser table must be regenerated or updated.",
  };
  const pivots = [{ path: "astropy/units/format/cds.py", source: "x" }];
  const withHints = { capsuleV2: { pivots, support: [], actionabilityHints: [hint] } };
  const withoutHints = { capsuleV2: { pivots, support: [], actionabilityHints: [] } };

  // The hint's relatedFile must NOT enter the file-path groups (no baseline read).
  const groups = runPipelineOutputFilePathGroups(withHints);
  const groupedPaths = groups
    .flat()
    .filter(Boolean)
    .map((bearer) => (bearer as { path?: string }).path);
  assert.ok(
    !groupedPaths.includes("astropy/units/format/cds_parsetab.py"),
    "related artifact must not be added to the naive full-file baseline",
  );

  const noopReader = async () => "";
  const accWith = await buildContextAccounting({
    repoRoot,
    emittedValue: withHints,
    filePathGroups: runPipelineOutputFilePathGroups(withHints),
    latencyMs: 1,
    reader: noopReader,
  });
  const accWithout = await buildContextAccounting({
    repoRoot,
    emittedValue: withoutHints,
    filePathGroups: runPipelineOutputFilePathGroups(withoutHints),
    latencyMs: 1,
    reader: noopReader,
  });
  // Rendered hint text is part of the serialized emitted value → more output tokens.
  assert.ok(
    accWith.estimatedOutputTokens > accWithout.estimatedOutputTokens,
    "hint text should increase estimatedOutputTokens",
  );
  // ...but the naive full-file baseline is identical (no extra file counted).
  assert.equal(
    accWith.estimatedNaiveFullFileTokens,
    accWithout.estimatedNaiveFullFileTokens,
  );
});
